name: Check
on:
  push:
    branches:
    - main
    - workflow_check
  pull_request:
    branches:
    - main

env:
  # Deny warnings
  RUSTFLAGS: -Dwarnings
  # Emit backtraces on panics.
  RUST_BACKTRACE: full

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: miri

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args:  --all --no-fail-fast

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all

      - name: Run cargo miri
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: miri
          args: test
